/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#001e5a",
        "error-container": "#9f0519",
        "on-primary": "#002873",
        "surface-container-highest": "#1b2055",
        "tertiary-fixed": "#fe9cf4",
        "primary-fixed": "#7b9cff",
        "on-primary-fixed-variant": "#00266e",
        "on-secondary-fixed-variant": "#6514d6",
        "on-surface-variant": "#a5a8d5",
        "error-dim": "#d7383b",
        "surface-container-high": "#161a4b",
        "on-primary-fixed": "#000000",
        "error": "#ff716c",
        "surface-dim": "#06092f",
        "surface-container": "#101442",
        "on-secondary": "#2b0065",
        "primary": "#90abff",
        "on-surface": "#e3e3ff",
        "primary-fixed-dim": "#658eff",
        "on-tertiary": "#722070",
        "inverse-on-surface": "#4f527a",
        "surface": "#06092f",
        "on-secondary-fixed": "#430097",
        "surface-variant": "#1b2055",
        "surface-tint": "#90abff",
        "secondary-fixed-dim": "#d0b8ff",
        "surface-container-lowest": "#000000",
        "primary-dim": "#316bf3",
        "secondary-fixed": "#dcc9ff",
        "on-tertiary-fixed": "#480049",
        "tertiary-dim": "#ef8fe5",
        "secondary-dim": "#8a4cfc",
        "surface-container-low": "#0a0e38",
        "tertiary": "#ffb4f4",
        "on-tertiary-container": "#661466",
        "inverse-primary": "#0053dc",
        "tertiary-container": "#fe9cf4",
        "secondary-container": "#6001d1",
        "surface-bright": "#212660",
        "inverse-surface": "#fbf8ff",
        "on-tertiary-fixed-variant": "#711f6f",
        "on-error-container": "#ffa8a3",
        "on-background": "#e3e3ff",
        "on-secondary-container": "#e1d0ff",
        "primary-container": "#7b9cff",
        "tertiary-fixed-dim": "#ef8fe5",
        "secondary": "#af88ff",
        "background": "#06092f",
        "on-error": "#490006",
        "outline-variant": "#41456c",
        "outline": "#6f729d"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "lg": "1rem",
        "xl": "1.5rem",
      },
    },
  },
  plugins: [],
}
